(function(root){
  'use strict';
  const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
  const emptyState=()=>({personaInstancesById:{},runPersonaPool:[],equippedPersonaInstanceIds:[null,null,null,null],dynamicPersonaTemplatesById:{},personaHistory:{usedHandTypes:[],previousHandType:null,sameHandTypeStreak:0}});
  function create({templates,stateStore,slotCount=4,now=()=>Date.now(),idFactory}={}){
    const staticTemplates=new Map((templates||[]).map(template=>[template.id,clone(template)]));let memory=emptyState();
    const store=stateStore||{get:()=>clone(memory),set:value=>{memory=clone(value)}};
    function normalizedState(value){return value&&value.personaInstancesById?{...emptyState(),...clone(value),dynamicPersonaTemplatesById:clone(value.dynamicPersonaTemplatesById||{})}:emptyState()}
    function getState(){return normalizedState(store.get?.())}
    function setState(value){store.set(clone(normalizedState(value)));return getState()}
    function getTemplate(id,state=getState()){return clone(staticTemplates.get(id)||state.dynamicPersonaTemplatesById?.[id]||null)}
    function templateForInstance(instance,state=getState()){return getTemplate(instance?.templateId,state)}
    function registerTemplate(template,{dynamic=true}={}){if(!template?.id)throw new Error('Persona template id is required');if(staticTemplates.has(template.id))return getTemplate(template.id);const state=getState();if(dynamic){state.dynamicPersonaTemplatesById[template.id]=clone(template);setState(state)}else staticTemplates.set(template.id,clone(template));return clone(template)}
    function validateState(value){const state=normalizedState(value);if(!Array.isArray(state.runPersonaPool)||!Array.isArray(state.equippedPersonaInstanceIds)||state.equippedPersonaInstanceIds.length!==slotCount)return false;if(new Set(state.equippedPersonaInstanceIds.filter(Boolean)).size!==state.equippedPersonaInstanceIds.filter(Boolean).length)return false;return Object.values(state.personaInstancesById||{}).every(instance=>root.PersonaInstance.validatePersonaInstance(instance,templateForInstance(instance,state)))&&state.equippedPersonaInstanceIds.filter(Boolean).every(id=>state.personaInstancesById[id])}
    function createInstance(templateId,meta={}){const state=getState(),template=getTemplate(templateId,state);if(!template)throw new Error(`Unknown persona template: ${templateId}`);const instance=root.PersonaInstance.createPersonaInstance(template,{...meta,createdAt:meta.createdAt||now(),instanceId:meta.instanceId||(idFactory?idFactory(templateId):undefined)});if(state.personaInstancesById[instance.instanceId])throw new Error(`Duplicate persona instance: ${instance.instanceId}`);state.personaInstancesById[instance.instanceId]=instance;state.runPersonaPool.push(instance.instanceId);setState(state);return clone(instance)}
    function initializeRun(templateIds=[],meta={}){setState(emptyState());templateIds.slice(0,slotCount).forEach((templateId,index)=>{const instance=createInstance(templateId,{...meta,source:meta.source||'SLICE_INITIAL'});equipPersona(instance.instanceId,index)});return getState()}
    function initializeLoadout(entries=[],meta={}){setState(emptyState());for(const [index,entry] of entries.slice(0,slotCount).entries()){if(entry.template)registerTemplate(entry.template);const instance=createInstance(entry.templateId,{...meta,...entry.meta,source:entry.source||meta.source||'BASE_PERSONA',instanceId:entry.instanceId});equipPersona(instance.instanceId,index)}return getState()}
    function equipPersona(instanceId,slotIndex){if(!Number.isInteger(slotIndex)||slotIndex<0||slotIndex>=slotCount)throw new Error('Invalid persona slot');const state=getState();if(!state.personaInstancesById[instanceId])throw new Error('Persona instance not in run pool');if(state.equippedPersonaInstanceIds.some((id,index)=>id===instanceId&&index!==slotIndex))throw new Error('Persona instance already equipped');state.equippedPersonaInstanceIds[slotIndex]=instanceId;setState(state);return clone(state.equippedPersonaInstanceIds)}
    function unequipPersona(slotIndex){if(!Number.isInteger(slotIndex)||slotIndex<0||slotIndex>=slotCount)throw new Error('Invalid persona slot');const state=getState(),removed=state.equippedPersonaInstanceIds[slotIndex];state.equippedPersonaInstanceIds[slotIndex]=null;setState(state);return removed}
    function replacePersona(slotIndex,instanceId){return equipPersona(instanceId,slotIndex)}
    function equippedWithSlots(state=getState()){return state.equippedPersonaInstanceIds.map((id,slotIndex)=>id?{instance:state.personaInstancesById[id],slotIndex}:null).filter(Boolean)}
    function equipped(state=getState()){return equippedWithSlots(state).map(entry=>entry.instance)}
    function applyRuleEffects(instance,template,effects,context,commit,source){const before=clone(instance.runtimeState),effectResult=root.PersonaEffectExecutor.execute(effects,{runtimeState:instance.runtimeState,caps:template.caps,commit,source});if(commit)instance.runtimeState=effectResult.runtimeState;return{...effectResult,runtimeBefore:before,runtimeAfter:clone(commit?instance.runtimeState:before),context:clone(context)}}
    function processEvent(event,context={},commit=false){const state=getState(),logs=[];for(const {instance,slotIndex} of equippedWithSlots(state)){const template=templateForInstance(instance,state),before=clone(instance.runtimeState);if((context.disabledSlotIndexes||[]).includes(slotIndex)){logs.push({instanceId:instance.instanceId,templateId:template.id,slotIndex,disabled:true,triggered:false,conditionResults:[],effectsApplied:[],chipsDelta:0,multDelta:0,finalMultiplierDelta:0,runtimeStateBefore:before,runtimeStateAfter:before});continue}for(const rule of template.growthRules||[]){if(rule.event!==event)continue;const conditionResults=root.PersonaConditionEvaluator.evaluateDetailed(rule.conditions,context,instance.runtimeState);if(conditionResults.some(item=>!item.passed))continue;const result=applyRuleEffects(instance,template,rule.effects,context,commit,template.name);logs.push({instanceId:instance.instanceId,templateId:template.id,slotIndex,triggered:true,conditionResults,effectsApplied:result.events,chipsDelta:result.chipsDelta,multDelta:result.multDelta,finalMultiplierDelta:result.finalMultiplier-1,runtimeStateBefore:result.runtimeBefore,runtimeStateAfter:result.runtimeAfter,runtimeBefore:result.runtimeBefore,runtimeAfter:result.runtimeAfter})}}if(commit)setState(state);return{logs,state:getState()}}
    function processDiscard(count,{commit=false,context={}}={}){return processEvent('DISCARD_COMMITTED',{...context,discardsUsedThisAction:count},commit)}
    function evaluateHand(context,{commit=false,scoreLayers={chips:0,mult:0,xmult:1}}={}){
      const state=getState(),history=state.personaHistory||emptyState().personaHistory,handKey=context.handTypeId||context.handType,predictedStreak=history.previousHandType===handKey?history.sameHandTypeStreak+1:1,fullContext={...context,sameHandTypeStreak:context.sameHandTypeStreak??predictedStreak,previousHandType:history.previousHandType,runHistory:clone(history)},aggregate={chipsDelta:0,multDelta:0,finalMultiplier:1,logs:[]},handActivations=new Map();
      for(const {instance,slotIndex} of equippedWithSlots(state)){const template=templateForInstance(instance,state),before=clone(instance.runtimeState),conditionResults=root.PersonaConditionEvaluator.evaluateDetailed(template.conditions,fullContext,instance.runtimeState);if((fullContext.disabledSlotIndexes||[]).includes(slotIndex)){aggregate.logs.push({instanceId:instance.instanceId,templateId:template.id,name:template.name,slotIndex,conditionResults,conditionsMet:false,triggered:false,disabled:true,effectsApplied:[],chipsDelta:0,multDelta:0,finalMultiplierDelta:0,runtimeStateBefore:before,runtimeStateAfter:before,runtimeBefore:before,runtimeAfter:before});continue}const conditionsMet=conditionResults.every(item=>item.passed),limit=template.activationLimit||{scope:'HAND',count:1},used=limit.scope==='BATTLE'?(instance.runtimeState.activationCountThisBattle||0):(handActivations.get(instance.instanceId)||0),allowed=used<limit.count;if(!conditionsMet||!allowed){aggregate.logs.push({instanceId:instance.instanceId,templateId:template.id,name:template.name,slotIndex,conditionResults,conditionsMet,triggered:false,effectsApplied:[],chipsDelta:0,multDelta:0,finalMultiplierDelta:0,runtimeStateBefore:before,runtimeStateAfter:before,runtimeBefore:before,runtimeAfter:before});continue}const repeatModifier=(template.successModifiers||[]).find(item=>item.type==='REPEAT_EFFECT_ONCE'&&item.condition==='FIRST_SUCCESSFUL_TRIGGER_THIS_BATTLE'),repeatKey=repeatModifier?.runtimeKey||'firstSuccessRepeated',repetitions=repeatModifier&&!instance.runtimeState[repeatKey]?2:1;let combined={chipsDelta:0,multDelta:0,finalMultiplier:1,events:[],runtimeBefore:before,runtimeAfter:before};for(let repeat=0;repeat<repetitions;repeat++){const result=applyRuleEffects(instance,template,template.effects,fullContext,commit,template.name);combined.chipsDelta+=result.chipsDelta;combined.multDelta+=result.multDelta;combined.finalMultiplier*=result.finalMultiplier;combined.events.push(...result.events.map(event=>({...event,repeatIndex:repeat})));combined.runtimeAfter=result.runtimeAfter}if(commit&&repeatModifier)instance.runtimeState[repeatKey]=true;combined.runtimeAfter=clone(commit?instance.runtimeState:before);aggregate.chipsDelta+=combined.chipsDelta;aggregate.multDelta+=combined.multDelta;aggregate.finalMultiplier*=combined.finalMultiplier;aggregate.logs.push({instanceId:instance.instanceId,templateId:template.id,name:template.name,slotIndex,conditionResults,conditionsMet:true,triggered:true,effects:combined.events,effectsApplied:combined.events,chipsDelta:combined.chipsDelta,multDelta:combined.multDelta,finalMultiplierDelta:combined.finalMultiplier-1,runtimeStateBefore:combined.runtimeBefore,runtimeStateAfter:combined.runtimeAfter,runtimeBefore:combined.runtimeBefore,runtimeAfter:combined.runtimeAfter});handActivations.set(instance.instanceId,used+1);if(commit&&limit.scope==='BATTLE')instance.runtimeState.activationCountThisBattle=used+1}
      if(commit){for(const {instance,slotIndex} of equippedWithSlots(state)){if((fullContext.disabledSlotIndexes||[]).includes(slotIndex))continue;const template=templateForInstance(instance,state);for(const rule of template.growthRules||[]){if(rule.event!=='HAND_COMMITTED'||!root.PersonaConditionEvaluator.evaluateAll(rule.conditions,fullContext,instance.runtimeState))continue;const result=applyRuleEffects(instance,template,rule.effects,fullContext,true,template.name),log=aggregate.logs.find(item=>item.instanceId===instance.instanceId);if(log){log.growthEffects=result.events;log.runtimeStateAfter=clone(instance.runtimeState);log.runtimeAfter=clone(instance.runtimeState)}}}if(!history.usedHandTypes.includes(handKey))history.usedHandTypes.push(handKey);history.previousHandType=handKey;history.sameHandTypeStreak=predictedStreak;state.personaHistory=history;setState(state)}
      const before=Math.round(scoreLayers.chips*scoreLayers.mult*scoreLayers.xmult),after=Math.round((scoreLayers.chips+aggregate.chipsDelta)*(scoreLayers.mult+aggregate.multDelta)*scoreLayers.xmult*aggregate.finalMultiplier);return{...aggregate,scoreBefore:before,scoreAfter:after,state:getState()};
    }
    function resetBattle(){const state=getState();for(const instance of Object.values(state.personaInstancesById)){const template=templateForInstance(instance,state),defaults=template.runtimeDefaults||{},scopes=template.runtimeScopes||{};for(const key of Object.keys(instance.runtimeState)){if(scopes[key]==='BATTLE'||key==='activationCountThisBattle')instance.runtimeState[key]=clone(defaults[key])}}state.personaHistory.previousHandType=null;state.personaHistory.sameHandTypeStreak=0;setState(state)}
    function restore(snapshot){if(!validateState(snapshot))throw new Error('Invalid Persona Runtime state');return setState(snapshot)}
    return{initializeRun,initializeLoadout,registerTemplate,createInstance,equipPersona,unequipPersona,replacePersona,getEquippedPersonas:()=>clone(equipped()),getState,restore,validateState,processDiscard,evaluateHand,resetBattle,getTemplate:id=>getTemplate(id)};
  }
  root.PersonaRuntime={create,emptyState};
})(globalThis);
